In [1]:
import pandas as pd
import sys
sys.path.insert(0,'../src')
from feature_selection_driver import FeatureSelectionDriver
from driver import Driver
from etl.zoo_etl import ZooEtl
from etl.iris_etl import IrisEtl

Using TensorFlow backend.

In [2]:
feature_dfs = []

In [3]:
def run_test(data_set,model_params,fimp_type,acc_percent_threshold=.9):
    if (model_params['model_type']=='log_reg')&(fimp_type=='shap'):
        return None
    driver = FeatureSelectionDriver(data_set, model_params,fimp_type)
    feature_df = driver.run(acc_percent_threshold, verbose=False)
    
    feature_df['data_set']=data_set
    feature_df['model_type']=model_params['model_type']
    feature_df['fimp_type']=fimp_type
    
    return feature_df

In [4]:
data_sets = ['iris','zoo','credit']

In [5]:
model_params_arr = [
    {'model_type':'log_reg', 'max_iter':100},
    {'model_type':'rf_class', 'n_estimators':100, 'max_depth':10},
    {'model_type':'nn', 'num_hidden_layers':4, 'nodes_per_layer':64, 'activation':'relu', 
     'optimizer':'adam', 'loss':'crossentropy', 'metrics':['accuracy'], 'num_epochs':20}
]

In [6]:
fimp_types = ['shap', 'perm']

In [7]:
verbose = True
for data_set in data_sets:
    for model_params in model_params_arr:
        for fimp_type in fimp_types:
            if (fimp_type=='shap')&(model_params['model_type']=='log_reg'):
                continue
            if verbose:
                print('Data:{}, Model:{}, Fimp:{}'.format(data_set,model_params['model_type'],fimp_type))
            feature_df = run_test(data_set,model_params,fimp_type)
            feature_dfs.append(feature_df)

Data:iris, Model:log_reg, Fimp:perm
Data:iris, Model:rf_class, Fimp:shap
Data:iris, Model:rf_class, Fimp:perm
Data:iris, Model:nn, Fimp:shap
Data:iris, Model:nn, Fimp:perm
Data:zoo, Model:log_reg, Fimp:perm
Data:zoo, Model:rf_class, Fimp:shap
Data:zoo, Model:rf_class, Fimp:perm
Data:zoo, Model:nn, Fimp:shap

/Users/justin/anaconda3/envs/p3-ml/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

Data:zoo, Model:nn, Fimp:perm
Data:credit, Model:log_reg, Fimp:perm
Data:credit, Model:rf_class, Fimp:shap
Data:credit, Model:rf_class, Fimp:perm
Data:credit, Model:nn, Fimp:shap

/Users/justin/anaconda3/envs/p3-ml/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

Data:credit, Model:nn, Fimp:perm

In [8]:
feature_dfs[11]

,features,num_features,val_acc,test_acc,continue,data_set,model_type,fimp_type
0,"[LIMIT_BAL, SEX, EDUCATION, MARRIAGE, AGE, PAY...",23,0.814865,0.822702,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, LIMIT_BAL, PAY_3, PAY_4, PAY_AM...",22,0.814524,0.822702,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, PAY_3, LIMIT_BAL, PAY_5, PAY_4,...",21,0.815888,0.823029,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, PAY_3, LIMIT_BAL, PAY_5, PAY_AM...",20,0.814183,0.824010,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, PAY_3, LIMIT_BAL, PAY_4, PAY_AM...",19,0.813502,0.823683,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, PAY_3, LIMIT_BAL, PAY_AMT1, PAY...",18,0.812820,0.826627,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, LIMIT_BAL, PAY_3, PAY_4, PAY_AM...",17,0.814183,0.823356,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, PAY_3, LIMIT_BAL, PAY_AMT1, PAY...",16,0.815206,0.822048,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, LIMIT_BAL, PAY_3, PAY_AMT1, PAY...",15,0.812820,0.821066,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, PAY_3, LIMIT_BAL, PAY_AMT1, PAY...",14,0.815547,0.823029,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, PAY_3, LIMIT_BAL, PAY_AMT1, PAY...",13,0.814865,0.823356,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, PAY_3, LIMIT_BAL, PAY_4, PAY_AM...",12,0.813842,0.822048,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, PAY_3, LIMIT_BAL, PAY_4, PAY_AM...",11,0.813161,0.822702,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, LIMIT_BAL, PAY_4, PAY_3, PAY_5,...",10,0.813161,0.823356,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, LIMIT_BAL, PAY_3, PAY_AMT1, PAY...",9,0.814183,0.822048,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, LIMIT_BAL, PAY_3, PAY_5, PAY_AM...",8,0.816911,0.824010,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, PAY_3, LIMIT_BAL, PAY_5, PAY_AM...",7,0.813842,0.821394,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, PAY_3, LIMIT_BAL, PAY_AMT3, PAY_5]",6,0.810774,0.822048,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, PAY_AMT3, PAY_3, LIMIT_BAL]",5,0.806683,0.822702,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, PAY_3, LIMIT_BAL]",4,0.807024,0.815833,True,credit,rf_class,shap
0,"[PAY_0, PAY_2, PAY_3]",3,0.813161,0.820085,True,credit,rf_class,shap
0,"[PAY_0, PAY_2]",2,0.812138,0.821721,True,credit,rf_class,shap
0,[PAY_0],1,0.813842,0.821394,True,credit,rf_class,shap